### ISSUE TITLE
Deprecated warning on Ember 2.6.1

### ISSUE THREAD

**Issue by shijistar** [Panman8201/ember-bootstrap-switch#15]
I'm using this great addon on Ember 2.6.1, but I find a deprecation warning in console.

``` r, engine='bash', count_lines
vendor.js:22593 DEPRECATION: [DEPRECATED] didInitAttrs called in <udesk-crm@component:bs-switch::ember436>. [deprecation id: ember-views.did-init-attrs] See http://emberjs.com/deprecations/v2.x#toc_ember-component-didinitattrs for more details.
        at logDeprecationStackTrace (http://crm.ud.com/site/assets/vendor.js:22575:19)
        at HANDLERS.(anonymous function) (http://crm.ud.com/site/assets/vendor.js:22682:7)
        at raiseOnDeprecation (http://crm.ud.com/site/assets/vendor.js:22605:12)
        at HANDLERS.(anonymous function) (http://crm.ud.com/site/assets/vendor.js:22682:7)
        at handleDeprecationWorkflow (http://crm.ud.com/site/assets/vendor.js:73769:9)
        at HANDLERS.(anonymous function) (http://crm.ud.com/site/assets/vendor.js:22682:7)
        at deprecationCollector (http://crm.ud.com/site/assets/vendor.js:73794:5)
        at HANDLERS.(anonymous function) (http://crm.ud.com/site/assets/vendor.js:22682:7)
        at http://crm.ud.com/site/assets/udesk-crm.js:4335:21
```

Is it on your plan to upgrade it to newer version of Ember in order to remove that?

**Comment by Panman82** [comment]
Yep, released a new version last week to remove this warning. Update to version 1.13.3 of this addon. 😄
